### ISSUE TITLE
Dúvida nas funções SEERRO (linhas 119,120 e 121 da Aba Relatório)

### ISSUE THREAD

**Issue by harleybarreto** [jeffersonpimenta/Planilha-SPDA#1]
Caro Jefferson, percebi que embora eu mudasse os parâmetros que antecedem as linhas 119, 120 e 121 os valores das células 
 O119, O120 e O121 nunca se alteravam (Planilha Análise de Risco - Aba Relatório).

As funções nessas células estão com o primeiro argumento "0", exemplo: =SEERRO(0;O70*O111*(O114/O118)).

Acredito que "zero" deveria ser o valor em caso da função encontrar um erro na equação avaliada, certo?

No mais parabéns pela planilha.

**Comment by harleybarreto** [comment]
Nas células O83 e O84 da Aba Estudo da planilha, está sendo usada a célula $R$24 na função SE. Porém essa célula é um "cabeçalho" e não uma variável como as células abaixo dela. Dessa forma a função retorna sempre "0". Caso eu tenha entendido certo, quais devem ser as células no lugar de $R$24?

**Comment by jeffersonpimenta** [comment]
Boa tarde!

O seerrro serve pra veriricar se a perca econômica é usada, poderia ter feito a verificação lá em baixo ou então checar se os parâmetros estavam zerados (método adotado).

Na aba estudo realmente é um erro, assim que corrigir faço o commit. Se tiver alguma sugestão de correção ficarei feliz pela contribuição.

Aliás, obrigado pelo feedback.

Abraços

**Comment by jeffersonpimenta** [comment]
Boa tarde!

Realmente são dois erros na tabela, o primeiro deveria ser =SEERRO(O70*O111*(O114/O118);0)

O segundo vou verificar com calma, mas acho que deveria ser linkado ao campo de análise econômica.

Aliás, obrigado pelo feedback.

Abraços

**Comment by jeffersonpimenta** [comment]
Correções feitas!
